export const API_BASE_URL = 'http://localhost:8080/ToGame-back-1.0-SNAPSHOT/to-game-api'

export const API_ENDPOINTS = {
    REGISTER: '/user/register',
    SIGN_IN: '/user/sign-in',
    USER_INFO: '/user/info',
    USER_INFO_BY_ID: '/user/info-by-id',
    USER_DELETE: '/user/delete',
    USER_UPDATE: '/user/update',
    UPDATE_AVATAR: '/user/update-avatar',
    DELETE_AVATAR: '/user/delete-avatar',
    SEND_LIKE: '/user/send-like',
    DELETE_FRIEND: '/user/delete-friend',
    GET_FRIENDS: '/user/get-friends',
    GET_RECIEVED_LIKES: '/user/get-recieved-likes',
    GET_SENT_LIKES: '/user/sent-likes',
    GAME_ALL: '/game/all',
    GAME_ALL_BY_USER: '/game/all-by-user',
    ADD_GAME: '/game/add-game',
    REMOVE_GAME: '/game/remove-game',
    CREATE_CHAT: '/chat/create',
    UPDATE_CHAT: '/chat/update',
    DELETE_CHAT: '/chat/delete',
    JOIN_CHAT: '/chat/join-chat',
    LEAVE_CHAT: '/chat/leave-chat',
    JOIN_ROOM: '/chat/join-room',
    LEAVE_ROOM: '/chat/leave-room',
    CREATE_ROOM: '/chat/create-room',
    DELETE_ROOM: '/chat/delete-room',
    SEND_MESSAGE: '/chat/send-message',
    GET_MESSAGES: '/chat/get-messages',
};

